### ISSUE TITLE
キャンバス編集モードのサイドツールバーのコンポーネントを作る

### ISSUE THREAD

**Issue by tipo122** [tipo122/synapse-genius#35]

**Comment by Kawanishi45** [comment]
このタスクはUI変更など踏まえ、一旦停止になっている認識です。

**Comment by tipo122** [comment]
@Kawanishi45 そうですね、このタスクはイテレーションから外してbacklogとしました。
新たなUIへの移行として、新しいタスクから開始したいと思いますので、これはクローズしてしまいます。
